language: android

jdk: oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd\n504667f4c0de7af1a06de9f4b1727b84351f2910" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - tools
    - tools

before_script: chmod +x gradlew

script: ./gradlew build

after_success: .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "HG2SDI/pIrNwLNk+KmWBExjQo/I+dTlPywJU9r7Xwm7yR+oK3B5MFjH7kZ3AHwbOibo7cvSnJfs7RhlYo/Ta3Z/AiIEskVzMRy9XLQHBRD9t4nkaa1GY98dWgjKnngaRvgcpvWgS3M2A69d8OnPNX858Ge2WchwXvd0bWTS5a9U="
    - secure: "O1Smf6Jli0+465ym+C2zV3ZLseA7/LRdgMCojNUU6bKLvM7SY5sGv47m0tlCdFKNvOUijFXYWYmcSpNWFZ7avQROFMKjWXGcE7aKTZsbh42+tzzqW8IYKWMzlH7d3ZbzALTvYVNLn6pdcRJOlHiC0ApnAMvfci8MG7d50xB3yQM="

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  timeout: 300 # 5 minutes
