language: android

# https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25

script:
  - ./gradlew check --debug

sudo: false

cache:
  directories:
    - $HOME/.gradle
