version: 2.1
jobs:
  build:
    working_directory: ~/gradle-play-publisher
    docker:
      - image: circleci/android:api-29
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ .Branch }}
            - v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Accept Android licenses
          command: |
            mkdir -p "$ANDROID_HOME/licenses"
            echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
            echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd\n504667f4c0de7af1a06de9f4b1727b84351f2910" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
      - run:
          name: Setup environment
          command: |
            chmod +x gradlew
            mkdir -p $HOME/.gradle
            echo "gradle.publish.key=$PUBLISH_KEY" > $HOME/.gradle/gradle.properties
            echo "gradle.publish.secret=$PUBLISH_SECRET" >> $HOME/.gradle/gradle.properties
            ./gradlew -Dbootstrap publishToMavenLocal
      - run:
          name: Build
          command: ./gradlew clean ciBuild --stacktrace
      - store_test_results:
          path: play/plugin/build/test-results
      - save_cache:
          key: v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ .Branch }}-{{ .Revision }}
          when: always
          paths:
            - ~/.gradle
